patterns = [" sp.",
            " aff.",
            " var.",
            " x ",
            " cf.",
            " TNS:",
            " SK-",
            " isolate BB",
            "subsp.",
            "(nom. inval.)"]
